theme: jekyll-theme-slate
name: Transfer Learning Approach for Classification and Noise Reduction on Noisy Web Data
title: Transfer Learning Approach for Classification and Noise Reduction on Noisy Web Data
description: Vehicle Recognition Project
